### ISSUE TITLE
feature request: account support

### ISSUE THREAD

**Issue by neoice** [phrack/imgur-Uploader#1]
Imgur recently added accounts (http://imgur.com/register/) and I'm guessing that people might want to link their Android uploads with their account. unfortunately, I have no Android dev skills whatsoever :/

**Comment by neoice** [comment]
it looks like this project might be dead.

**Comment by phrack** [comment]
Yes, this project died because people wanted to be able to use imgur accounts and a competing solution added support for this before this application did. The code is still up in case it happens to be useful to someone some day.
